-- Dimension tables

CREATE TABLE DIM_DEPARTMENTS(
 DEPARTMENT_ID Bigint NOT NULL,
 DEPARTMENT Character varying(127),
 CONSTRAINT PK_DIM_DEPARTMENTS PRIMARY KEY (DEPARTMENT_ID)
)
DISTRIBUTED REPLICATED
;

CREATE TABLE DIM_AISLES(
 AISLE_ID Bigint NOT NULL,
 AISLE Character varying(127),
 CONSTRAINT PK_DIM_AISLES PRIMARY KEY (AISLE_ID)
)
DISTRIBUTED REPLICATED
;

CREATE TABLE DIM_PRODUCTS(
 PRODUCT_ID Bigint NOT NULL,
 PRODUCT_NAME Character varying(255),
 AISLE_ID Bigint,
 DEPARTMENT_ID Bigint,
 CONSTRAINT PK_DIM_PRODUCTS PRIMARY KEY (PRODUCT_ID)
)
DISTRIBUTED REPLICATED
;

CREATE INDEX PRODUCT_AISLE_IX ON DIM_PRODUCTS (AISLE_ID)
;

CREATE INDEX PRODUCT_DEPARTMENT_IX ON DIM_PRODUCTS (DEPARTMENT_ID)
;

CREATE TABLE DIM_DATES(
 REPORT_DATE Date NOT NULL,
 DAY_OF_WEEK Smallint NOT NULL,
 IS_HOLIDAY Boolean NOT NULL,
 CONSTRAINT PK_DIM_DATES PRIMARY KEY (REPORT_DATE)
)
DISTRIBUTED REPLICATED
;

CREATE TABLE DIM_LOCATION_AREAS(
 AREA_ID Bigint NOT NULL,
 AREA Character varying(64),
 CONSTRAINT PK_DIM_LOCATION_AREAS PRIMARY KEY (AREA_ID)
)
DISTRIBUTED REPLICATED
;

CREATE TABLE DIM_CLIENTS(
 ID Bigint NOT NULL,
 FULLNAME Character varying(63),
 LOCATION_AREA_ID Bigint,
 CONSTRAINT PK_DIM_CLIENTS PRIMARY KEY (ID)
)
DISTRIBUTED REPLICATED
;

CREATE INDEX CLIENTS_LOCATION_IX ON DIM_CLIENTS (LOCATION_AREA_ID)
;


CREATE TABLE DIM_STORE_TYPES(
 STORE_TYPE_ID Bigint NOT NULL,
 TYPE Character varying(64),
 CONSTRAINT PK_DIM_STORE_TYPES PRIMARY KEY (STORE_TYPE_ID)
)
DISTRIBUTED REPLICATED
;


CREATE TABLE DIM_STORES(
 STORE_ID Bigint NOT NULL,
 LOCATION_AREA_ID Bigint,
 STORE_TYPE_ID Bigint,
 CONSTRAINT PK_DIM_STORES PRIMARY KEY (STORE_ID)
)
DISTRIBUTED REPLICATED
;

CREATE INDEX STORES_LOCATION_IX ON DIM_STORES (LOCATION_AREA_ID)
;

CREATE INDEX STORE_TYPE_IX ON DIM_STORES (STORE_TYPE_ID)
;





--Fact tables

CREATE TABLE FACT_ORDERS(
 REPORT_DATE Date NOT NULL,
 PRODUCT_ID Bigint NOT NULL,
 CLIENT_ID Bigint NOT NULL,
 STORE_ID Bigint NOT NULL,
 QUANTITY Bigint NOT NULL
)
--WITH (appendoptimized=true, orientation=row)
--DISTRIBUTED BY (REPORT_DATE)
--PARTITION BY RANGE (REPORT_DATE)
--( START (date '2021-01-01') INCLUSIVE
--   END (date '2021-12-31') INCLUSIVE
--   EVERY (INTERVAL '1 day')
--)
DISTRIBUTED REPLICATED
;


CREATE TABLE FACT_OOS(
 REPORT_DATE Date NOT NULL,
 PRODUCT_ID Bigint NOT NULL
)
--WITH (appendoptimized=true, orientation=row)
--DISTRIBUTED BY (REPORT_DATE)
--PARTITION BY RANGE (REPORT_DATE)
--( START (date '2021-01-01') INCLUSIVE
--   END (date '2021-12-31') INCLUSIVE
--   EVERY (INTERVAL '1 day')
--)
DISTRIBUTED REPLICATED
;


